name       : python-omemo-dr
version    : 1.0.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/o/omemo-dr/omemo-dr-1.0.0.tar.gz : b0fe5023e947a17b740fb7ed4aa246120d6f21d819b5812e94dfc9570520be61
homepage   : https://dev.gajim.org/gajim/omemo-dr
license    : GPL-3.0-or-later
component  : programming.python
summary    : OMEMO Crypto Library
description: |
    This library handles only the crypto part of OMEMO, not the XMPP protocol part. This means you need to take care yourself of things like publishing/downloading bundles, publishing/subscribing to PEP deviceliste updates, sending and receiving messages.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
rundeps    :
    - python-cryptography
    - python-protobuf
build      : |
    %python3_setup
install    : |
    %python3_install
